### ISSUE TITLE
data-type must be one of the values: svg, script from php 

### ISSUE THREAD

**Issue by elteto** [AnyChart/export-server#2]
I receive the following error when executing the following code in php

> {
>     "error": "data-type must be one of the values: svg, script"
> }

This is my code using the sample in (https://docs.anychart.com/Common_Settings/Server-side_Rendering)

when i run in console, with curl, its Ok. but from php give an error.
```
<?php
$params=[
	'responseType'=>'file', 
	'dataType'=>'script',
	'data'=>'var chart = anychart.line([1,2,5]); chart.container("container"); chart.draw();',
	];

$headers = array('Content-Type: application/x-www-form-urlencoded');
	
$defaults = array(
		CURLOPT_URL=>'http://localhost:3000/jpg',
		CURLOPT_POST => true,
		CURLOPT_POSTFIELDS => $params,
		CURLOPT_HTTPHEADER=> $headers
);

$ch = curl_init();
curl_setopt_array($ch, $defaults);
$picture = curl_exec($ch);
curl_close($ch);

$fh = fopen('filename.jpg', 'w');
fwrite($fh, $picture);
fclose($fh);
?>
```

**Comment by Shestac92** [comment]
@elteto 
There are two things to correct in your php code. 

1. All items in $params should be represented as a single string.

2. You should add CURLOPT_FILE to define the output for CURL.

3. The current version of export-server has some issues with exporting to jpg. I'd like to suggest you use the dev-preview of upcoming version. You can download it from [our CDN](https://cdn.anychart.com/export-server/export-server-NIIT-dev-preview-v5-custom-bundle.jar).

Below is your modified PHP code which was tested and works well:
`<?php
$fh = fopen('filename.jpg', 'w+');
 
$params=[
    'responseType'=>'file',
    'dataType'=>'script',
    'data'=>'var chart = anychart.line([1,2,5]); chart.container("container"); chart.draw();',
    ];
 
$data = "responseType=file&dataType=script&data=var chart = anychart.line([1,2,5]); chart.container('container'); chart.draw()";
 
$headers = array('Accept: application/json');
    
$defaults = array(
        CURLOPT_URL=>'http://localhost:2000/jpg',
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $data,
        CURLOPT_HTTPHEADER=> $headers,
        CURLOPT_FILE=> $fh
);
 
$ch = curl_init();
curl_setopt_array($ch, $defaults);
$picture = curl_exec($ch);
curl_close($ch);
  
fwrite($fh, $picture);
fclose($fh);
?>`

**Comment by elteto** [comment]
It works!
Thanks!
